stringsync/vexml

- index.ts
- indexWebpack.html
- lib/vexml/EasyScoreMessageProducer.ts
- lib/vexml/EasyScoreMessageRenderer.ts
- lib/vexml/MusicXMLCursor.ts
- lib/vexml/MusicXMLParser.ts
- lib/vexml/types.ts
- lib/vexml/vexml.ts
- package-lock.json
- package.json
- webpack.config.js
@jaredjj3 what do you think about this a pproach to read the xml file?
> reading input from xml files

- dev/public/examples/passacaglia.xml
- src/producer.ts
- src/renderer.ts
- src/types.ts
I have added passacaglia.xml. It is only printing the first two measures fixed width.
> measure start & end messages

- src/producer.ts
- src/renderer.ts
> refactor: removal of the Map

- dev/public/examples/OSMD_function_test_chord_symbols.xml
- src/producer.ts
- src/renderer.ts
- src/types.ts
I tried to render the first score from OSMD and dots were missing.
I have also changed the number of measures to render to 3.
It is a minor chnage and I will merge. We can always roll back changes.
> dots added

- src/producer.ts
- src/renderer.ts
- src/types.ts
This fixes test 01f (more accidentals types added) and adds support for cautionary accidentals.
> accidental cautionary support

- src/producer.ts
- src/renderer.ts
- src/types.ts
This fixes a lot of the unofficial MusicXML tests.
It also considers your comment not to use maps on the messages.
> clef refactoring

- src/renderer.ts
fixes #31 
With this one we can close #31. Now the scores are complete.
> multiline support

- src/renderer.ts
fixes #29 
@jaredjj3 I decided to give at a try at the usage of literal. I think that with this approach even `renderer.ts` gets easier to understand and maintain.
the generated code from passacaglia.mxl goes from 13749 lines to 8451 and it is much more simple.
> refactor literal

- src/producer.ts
- src/renderer.ts
- src/types.ts
Most of the new features can be seen in test 32a. I will go for ornaments after this one.
> articulations support

- src/producer.ts
- src/renderer.ts
- src/types.ts
A lot of progress with notations, I have also refactored to reduce the number of messages.
> notations & beam refactored

- src/producer.ts
- src/renderer.ts
- src/types.ts
Fixes #43 
The standard ones are there. :)
> simple time signatures support

- src/renderer.ts
I added `string` support on technical notations
> string support

- src/cursor.ts
- src/producer.ts
- src/renderer.ts
- src/types.ts
Fixes #36
Only basic support. We should start to divide renderer.ts in different files
> basic part support

- src/notations.ts
- src/renderer.ts
This is a possible way of reducing complexity. What do you think?
> new class: notations

- src/attributes.ts
- src/renderer.ts
Message attributes handled in a separate class
> new class: attributes

- package.json
- src/notations.ts
- src/renderer.ts
- yarn.lock
Most grace notes do not overlap now
Factory.Ornament now provided by VexFlow
> vexflow 4.0.3

- src/producer.ts
- src/renderer.ts
- src/types.ts
Basic support for lyrics. Yo will see that in 32a-Notations there are no overlaps
-
> LyricMessage support

- src/producer.ts
- src/renderer.ts
- src/types.ts
There is some work to do in VexFlow to get all the possibilites right and this can also be separated on an independent class.
However I believe that it can be merged as a starting point. :)
> BarlineMessage support

- src/producer.ts
- src/renderer.ts
- src/types.ts
Some progress :)
Changes will be visible once https://github.com/0xfe/vexflow/pull/1401 is merged in vexflow.
> more noteheads supported

- package.json
- src/attributes.ts
- src/producer.ts
- src/renderer.ts
- yarn.lock
Hi @jaredjj3, I decided to include vexflow tgz to make progress.
Fixes #54 
Fixes #42
> refactored to use System, vexflow included

- src/renderer.ts
Octave changes are not being kept this requires a change in VexFlow as referenced in the issue.
I have started writing comments :)
> render Clefs on new lines

- src/attributes.ts
- src/di.test.ts
- src/di.ts
- src/index.test.ts
- src/index.ts
- src/legacyproducer.ts
- src/measurehandler.test.ts
- src/measurehandler.ts
- src/msg.test.ts
- src/namednode.test.ts
- src/nodehandler.test.ts
- src/noophandler.test.ts
- src/noopreceiver.test.ts
- src/parthandler.test.ts
- src/parthandler.ts
- src/producer.test.ts
- src/producer.ts
- src/renderer.ts
- src/todohandler.test.ts
- src/todohandler.ts
- src/types.test.ts
- src/types.ts
- src/xml.test.ts
- src/xml.ts
Continuing to run with the refactoring idea, using PRs as soft status updates.
> Rename old producer to LegacyProducer and start work on new producer

- src/legacyproducer.ts
- src/msg.ts
- src/renderer.ts
- src/types.ts
> arpeggiate support added

- src/di.ts
- src/producers/directionhandler.test.ts
- src/producers/directionhandler.ts
- src/producers/measurehandler.test.ts
- src/producers/measurehandler.ts
- src/receivers/renderer.ts
- src/types.ts
- src/util/msg.ts
- src/util/xml.ts
@jaredjj3 two new features with the new structure, hopefullly!
> coda & segno

- src/rendering/README.md
This PR updates the `rendering` intent doc based on the changes made in #183.
> Update rendering intent doc

- README.md
> Update README.md with motivation

- site/src/components/CursorForm.tsx
- site/src/components/Vexml.tsx
- site/src/lib/Player.ts
- site/src/types.ts
- src/components/simplecursor.ts
- src/cursors/cursor.ts
- src/index.ts
- src/rendering/rendering.ts
This PR fixes several issues with the site player and cursors. It's still not perfect, but I think it's good enough to move forward with development of the continuous/smooth cursor.
> Make various player fixes for the site

- site/src/components/Vexml.tsx
- site/src/lib/Player.ts
- src/components/simplecursor.ts
- src/cursors/cursor.ts
- src/cursors/expensivelocator.ts
- src/playback/durationrange.ts
- src/playback/index.ts
- src/playback/sequence.ts
- src/playback/timestamplocator.ts
- src/rendering/events.ts
- src/rendering/index.ts
- src/rendering/locator.ts
- src/spatial/types.ts
- src/util/numberrange.ts
- src/vexml.ts
- tests/unit/util/numberrange.test.ts
For #158:
- Adds the ability to toggle the visibility of the cursor through the component (not a feature in the site).
- Creates a `playback.TimestampLocator` whose purpose is to find a timestamp given a `spatial.Point`.
- Moves the complexity of determining interpolation bounds to the Sequence.
- Adds the ability to click-to-seek via events.
- Allows small mouse movements when processing `mousedown` events.
https://github.com/user-attachments/assets/00135ece-04d1-4ef2-9819-a5ab92b1d8e7
> Make SimpleCursor visibility toggleable and add timestamp to events

- site/src/components/Vexml.tsx
- site/src/util/getDevice.ts
- src/cursors/cursor.ts
- src/cursors/scroller.ts
This PR fixes #250 by allowing callers to specify `'smooth' | 'instant' | 'auto' ` scroll behaviors.
I attempted to promisify scrolling, but it ultimately felt clunky and laggy. Detecting when the scroll was finished didn't always work so I had to resort to using a reasonable timeout of 500ms.
Another complexity I had to deal with was not being able to distinguish programmatic scrolls from user scrolls. To work around this, I disabled user scrolling during the programmatic scroll, but this made the rendering feel unresponsive.
I decided that it really is up to the caller's responsibility on what browsers they want to support and how they want to support them. Smooth scrolling can work on mobile, the caller just has to be wary not to spam `Cursor.scrollIntoView`  (I'm spamming it every …
> Allow callers to specify scroll behavior
