stringsync/vexml

- README.md
- dev/public/manifest.json
- dev/src/index.ts
- dev/webpack.config.js
Prior to this PR, a dev would have to add an example file to `dev/public/examples` and add an entry to `dev/public/manifest.json`. This PR adds a `/manifest` endpoint, which dynamically fetches what files are in `dev/public/examples`, which makes it easier to add examples.
> Improve dev server

- dev/src/components/Examples.tsx
- dev/src/components/RenderStatus.tsx
- dev/src/components/StatusSummary.tsx
- dev/src/components/Vexml.tsx
- dev/src/hooks/useConstant.ts
- dev/src/hooks/useLocalStorage.ts
- dev/src/hooks/useSettings.ts
The motivation for this PR was to address the poor performance when rendering the index page. This was partly due to the number of renders that the `<AlphabeticalIndex>` component had to do every time a render status changed. Now, the `<AlphabeticalIndex>` component is rendered after all of the examples finish rendering.
- adds `success`, `failed`, and `slowest` filters to the dev app
- adds stats to the dev app
- improves performance on the initial load
- saves settings in `LocalStorage`, so filters persist on hot reload
>NOTE: Toggling the "success" examples is still laggy. I think this is due to 100+ elements being updated at once. I'm not planning to fix this since it's a minor inconvenience.
> Add filters to dev app

- dev/src/components/Example.tsx
This PR partially addresses #24. It adds a "copy code" button to each example:
In a downstream PR, I will either add a lazily loaded embedded jsfiddle with the code prepopulated or a link that opens jsfiddle in a new tab with the code prepopulated.
> Add Copy Code button

- src/vexml.ts
I removed beam post format before anything was drawn.
Before:
After:
> Fix beaming

- src/README.md
- src/musicxml/README.md
- src/rendering/README.md
This PR adds documentation that explains the intent and design of each sub-library within `vexml`. I expect them to undergo many revisions the more we discover developing the library to 1.0.0.
> Document each sublibrary

- src/rendering/chorus.ts
- src/rendering/score.ts
- src/rendering/stave.ts
- src/rendering/voice.ts
This PR is a refactor of the multi voice support implemented in https://github.com/stringsync/vexml/pull/120. It moves the responsibility of calculating aggregate voice entry data to a new abstraction called `Chorus`.
This is particularly useful for calculating things like stem direction, where all the voices are needed. That way, `rendering.Voice` can focus on just creating a single `vexflow.Voice` without having to know anything about the other voices in the stave/measure.
> Distribute Voice creation complexity

- README.md
- package.json
- scripts/resnap.js
- tests/unit/musicxml/note.test.ts
This PR adds the `yarn resnap` command, which scripts out switching to a clean branch, then updating the tmp snapshots. This particularly improves the DX running tests outside of Docker.
> Add resnap command

- Dockerfile
- package.json
- Fix permissions of `/vexml` folder tree to allow installing packages and writing files
- Fix `package.json` `test` script for volume-mounting syntax that is compatible with Linux
> Fix docker-based test running #123

- src/musicxml/attributes.ts
- src/musicxml/clef.ts
- src/musicxml/defaults.ts
- src/musicxml/enums.ts
- src/musicxml/index.ts
- src/musicxml/key.ts
- src/musicxml/measurestyle.ts
- src/musicxml/note.ts
- src/musicxml/print.ts
- src/musicxml/stavedetails.ts
- src/musicxml/time.ts
- src/musicxml/types.ts
- src/rendering/README.md
- src/rendering/chorus.ts
- src/rendering/config.ts
- src/rendering/measure.ts
- src/rendering/measurefragment.ts
- src/rendering/part.ts
- src/rendering/score.ts
- src/rendering/stave.ts
- src/rendering/system.ts
- src/rendering/title.ts
- tests/unit/musicxml/attributes.test.ts
- tests/unit/musicxml/clef.test.ts
- tests/unit/musicxml/defaults.test.ts
- tests/unit/musicxml/measurestyle.test.ts
- tests/unit/musicxml/note.test.ts
- tests/unit/musicxml/print.test.ts
- tests/unit/musicxml/staffdetails.test.ts
This PR updates terms that use "staff" to use "stave" instead. Direct-ish references to musicXML were left untouched.
https://en.wikipedia.org/wiki/Staff_(music)
When I initially studied musicXML and vexflow, I didn't realize these terms were interchangeable. I thought "stave" / "staves" were the plural of "staff", so I was confused when I saw "stave" and "staff" used interchangeably. Hopefully this saves someone else the headache.
Good thing I used TypeScript.
> Migrate staff* references to stave*

- src/rendering/enums.ts
- src/rendering/rest.ts
This PR removes a problematic `NoteDurationDenominator` and an unused import.
> Clean up minor issues

- README.md
- package.json
- site/src/components/Controls.tsx
- site/src/components/Vexml.tsx
- src/README.md
- src/musicxml/musicxml.ts
- src/mxl/README.md
- src/mxl/container.ts
- src/mxl/index.ts
- src/mxl/mxl.ts
- src/mxl/rootfile.ts
- src/util/xml.ts
- src/vexml.ts
- tests/integration/lilypond.test.ts
- tests/unit/musicxml/musicxml.test.ts
- tests/unit/mxl/container.test.ts
- tests/unit/mxl/rootfile.test.ts
- tests/unit/util/vexml.test.ts
- yarn.lock
> Support compressed MusicXML

- src/rendering/chorus.ts
- src/rendering/measurefragment.ts
- src/rendering/spanners.ts
- src/rendering/tuplet.ts
This PR is a no-op due to the way `Spanners` are instantiated for each `MeasureFragment` at width measuring time. However, I wanted to make it more semantically accurate by explicitly checking tuplet membership within a measure fragment when deciding how much extra width to add.
> Fix spanners extra width calculation

- src/rendering/beam.ts
- src/rendering/score.ts
This PR fixes the issue called out in https://github.com/stringsync/vexml/issues/78#issuecomment-1874242859.
Before this PR, `vexflow.Beam` objects would try to be created with less than 2 stemmable notes, during the measurement phase or due to invalid MusicXML documents. This would cause a `vexflow` error to be thrown.
After this PR, we will simply check the stemmable notes length and ignore underspecified beams.
> Do not render incomplete beams

- site/src/components/SourceDisplay.tsx
- site/src/components/SourceInput.tsx
- site/src/components/SourceWorkspace.tsx
- site/src/components/Vexml.tsx
- site/src/hooks/useSources.ts
- site/src/types.ts
- site/src/util/downloadCanvasAsImage.ts
- site/src/util/downloadSvgAsImage.ts
- src/events/nativebridge.ts
- src/rendering/rendering.ts
- src/rendering/score.ts
- src/rendering/types.ts
- src/vexml.ts
- tests/integration/lilypond.test.ts
- tests/integration/vexml.test.ts
- tests/unit/util/vexml.test.ts
This PR fixes #228.
- Rename `vexml.Vexml.renderSVG` to `vexml.Vexml.render`. Callers can opaquely provide an `HTMLDivElement | HTMLCanvasElement` for as a container, and vexml will detect and render the correct thing.
- Update site to have a toggle for SVG or Canvas on a per-source basis.
- Encode vexml rendering mode into the source data (which is in localstorage). That way, when developing locally, the rendering mode is preserved between loads.
- Add snapshot support for `<canvas>` elements.
> Add canvas support

- site/src/components/EventTypeForm.tsx
- site/src/components/SourceDisplay.tsx
- site/src/components/SourceForm.tsx
- site/src/components/Vexml.tsx
- site/src/constants.ts
- site/src/hooks/useWidth.ts
- src/README.md
- src/components/README.md
- src/components/index.ts
- src/components/root.ts
- src/config/t.ts
- src/cursors/pointcursor.ts
- src/events/nativebridge.ts
- src/rendering/events.ts
- src/rendering/interactions.ts
- src/rendering/locator.ts
- src/rendering/rendering.ts
- src/rendering/rest.ts
- src/rendering/score.ts
- src/spatial/quadtree.ts
- src/spatial/rect.ts
- src/vexml.ts
- tests/integration/__data__/vexml/events.musicxml
- tests/integration/events.test.ts
- tests/integration/lilypond.test.ts
- tests/integration/vexml.test.ts
- tests/unit/util/vexml.test.ts
This PR fixes #227 by adding a basic event system. It adds an overlay element, which makes the event behavior consistent between SVG and canvas. Without this, SVG elements would "steal" touchend and touchcancel. I decided to leave the event system very bare and simple for now. I'll try to revisit before 1.0.0.
> Add more event support

- site/src/components/Vexml.tsx
- site/src/lib/Player.ts
- src/cursors/cursor.ts
- src/util/math.ts
This PR implements `Cursor.seek`, which is the interpolated alternative to `Cursor.snap`.
https://github.com/user-attachments/assets/e56e163f-a625-48cc-816b-a99b6e735bb0
It also supports repeats!
https://github.com/user-attachments/assets/1c41c1c9-2dc8-4903-af03-7b8242447f9a
Next, I think I'll introduce a max height for the vexml container, and allow the cursor to scroll the container if the cursor is not in view. This will be an option that's controlled in `Cursor.seek` or `Cursor.snap`.
> Implement smooth interpolated seeking

- site/src/components/ConfigForm.tsx
- site/src/components/SourceDisplay.tsx
- site/src/components/SourceForm.tsx
- site/src/components/SourceWorkspace.tsx
- site/src/components/Vexml.tsx
- site/src/hooks/useSources.ts
- site/src/lib/Player.ts
- site/src/types.ts
- src/components/overlay.ts
- src/components/root.ts
- src/cursors/cursor.ts
- src/cursors/scroller.ts
- src/events/nativebridge.ts
- src/playback/sequence.ts
- src/rendering/events.ts
- src/rendering/rendering.ts
- src/vexml.ts
This PR adds `Cursor.isFullyVisible` and a `scroll: boolean` option to `Cursor.snap` and `Cursor.seek`. It is the caller's responsibility to decide if to scroll or not. By being less prescriptive about how a MusicXML document should be scrolled, there are different scroll schemes that can be done. For example:
- scroll whenever the cursor is not fully visible (this is what's on the site)
- scroll whenever the cursor changes systems
- "paged" scrolling: assign systems to a page, then only scroll when the page changes
- etc.
The caller can also listen to the rendering's `scroll` event.
> [!NOTE]  
> `scrollTo` with `behavior: 'smooth'` is asynchronous, but the API is synchronous. It's possible to get in a bad scroll state if changed too quickly. …
> Allow rendering to be automatically scrolled based on cursor

- src/config/config.ts
- src/rendering/measure.ts
This PR fixes #252. The `ENABLE_MEASURE_NUMBERS` config has been replaced by `MEASURE_NUMBERING_SCHEME`.
> Add MEASURE_NUMBERING_SCHEME config

- src/drawables/circle.ts
- src/drawables/rect.ts
- src/index.ts
- src/playback/sequence.ts
- src/rendering/index.ts
- src/rendering/locator.ts
- src/rendering/measure.ts
- src/rendering/score.ts
- src/rendering/seed.ts
- src/rendering/types.ts
- src/vexml.ts
I realized that `MessageMeasure` can be generically used for any non-musical pause. I rename it to `Gap` and updated the public interface accordingly.
> Rename MessageMeasure to Gap and refactor

- src/rendering/stave.ts
PR #267 didn't fully fix #261 — it only fixed metronomes in the absolute first fragment of the score. This PR fully fixes #261 by requiring **all** rendered metronomes to be in the first part and first stave (not necessarily absolute first).
This fix should be included in ^0.1.3.
Before
After
> Fix metronome rendering when changing mid-score

- README.md
- src/elements/score.ts
- src/playback/sequencefactory.ts
This PR partially fixes #264. It will be included in ^0.1.3
It updates `SequenceFactory` to account for multiple staves in a part. However, it does not cover all edge cases. I created #270 to follow up.
> Fix playback sequence/cursor issues

- src/elements/score.ts
- src/playback/cursor.ts
- src/playback/types.ts
This PR fixes #264 by adding a mechanism to specify a cursor span. It `span` is `undefined`, it will default to spanning across all parts.
```ts
score.addCursor({ partIndex: 0, span: { fromPartIndex: 0, toPartIndex: 1 });
```
Before
After
> Implement cursor spans

- src/elements/score.ts
- src/playback/cursor.ts
- src/playback/defaultcursorframe.ts
- src/playback/elementdescriber.ts
- src/playback/hintdescriber.ts
- src/playback/index.ts
- src/playback/lazycursorstatehintprovider.ts
- src/playback/legacymeasuresequenceiterator.ts
- src/playback/timeline.ts
- src/playback/types.ts
- tests/unit/playback/defaultcursorframe.test.ts
- tests/unit/playback/lazycursorstatehintprovider.test.ts
- tests/unit/playback/measuresequenceiterator.test.ts
- tests/unit/playback/timeline.test.ts
This PR fixes #281. It will be released in 0.1.8.
- This PR formalizes the describer pattern and uses it in existing Timeline and CursorFrame tests.
- Marks MeasureSequenceIterator as LegacyMeasureSequenceIterator to communicate intent of eventually replacing it.
> Fix hints and improve unit tests
